### ISSUE TITLE
installation is not progressing

### ISSUE THREAD

**Issue by yasinyilmaz1** [yolanmees/Spikster#10]
When I install spikster on the Ubuntu 22.04 virtual server created on KVM, the tab key or the "OK" button in the area in the screenshot does not work during the ongoing process. I tried this from the terminal as well as from the vnc window, but it gets stuck there.

![Screenshot from 2023-10-04 03-40-11](https://github.com/yolanmees/Spikster/assets/80541213/4f0be506-fb68-4daf-bcb3-2f62d44797a7)

**Comment by yolanmees** [comment]
Hi,

This is because the new NEEDRESTART package in Ubuntu.
Run the following command before installing Spikster, this should do the trick. 

```
sudo NEEDRESTART_SUSPEND=1 apt-get dist-upgrade --yes
```

Let me know if this works and I will add it to the installer.

**Comment by yasinyilmaz1** [comment]
> Do you mind trying to disable it manually?
> 
> `/etc/needrestart/needrestart.conf` file, changing the line:
> 
> `#$nrconf{restart} = 'i';`
> 
> to
> 
> `$nrconf{restart} = 'a';`

Stuck at "PHP installation..." stage

![Screenshot from 2023-10-04 17-38-56](https://github.com/yolanmees/Spikster/assets/80541213/707482e9-68c1-4fa0-af17-5b0514712817)

**Comment by yasinyilmaz1** [comment]
After much effort, I completed the installation and was able to access the panel login information screen with the ssh username, password and database information, but the panel cannot be accessed.

![Uploading Screenshot from 2023-10-04 19-36-41.png…]()

**Comment by yolanmees** [comment]
I am sorry, I need to change this in the docs. 
its admin@localhost and password as email and password. 

You can change it on your user profile by clicking on your name in the dashboard.

**Comment by yasinyilmaz1** [comment]
Yes, I accessed the panel with the information you provided, but I rebooted the server and the result is like this

![Screenshot from 2023-10-06 01-37-22](https://github.com/yolanmees/Spikster/assets/80541213/84a98144-f0fd-4ec0-8ceb-9c4c66383e7b)

**Comment by yolanmees** [comment]
An what page is this? Do you have any logs?

**Comment by salocinyeet** [comment]
So I had the same situation. Got stuck on that screen. But after `sudo NEEDRESTART_SUSPEND=1 apt-get dist-upgrade --yes`
It did go thru. But I believe that there is an issue because now I get a Internal Server Error
<img width="486" alt="Screenshot 2024-03-15 at 08 47 01" src="https://github.com/yolanmees/Spikster/assets/32781165/83ac9f58-4fd0-42a9-ae90-aee17bb7ac1f">
Maybe because I had to exit the program mid way thru installation
